services:
  faturamentosapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - pedidos-network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:7.0
    container_name: faturamentosapi-mongodb
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongodb_data:/data/db
    networks:
      - pedidos-network

volumes:
  mongodb_data:

networks:
  pedidos-network:
    driver: bridge
